// @ts-nocheck

export function essayMeta(slug) {
  const meta = {
    "jaya": {
      tags: "optimisation, feature selection, bioinformatics",
      toc: ["Header", "Lede", "JAYA, briefly", "Two modifications", "Three protein datasets", "What improved means"],
      sources: [
        ['[1] Rao, R. V. (2016). ', '"Jaya: A simple and new optimization algorithm." Int. J. Industrial Engineering Computations.'],
        ['[2] Gandhi, N., Sharma, S., Rawat, O., Bhosale, H., Sane, A., & Jayaraman, V. K. (2022). ', '"Improved Jaya algorithm for identification of protein functions." Poster PP-28, INBIX\'22, VFSTR.'],
        ['[3] ', "github.com/shubhangithub/inbix22"],
      ],
      sidenotes: 4,
    },
    "threshold-gate": {
      tags: "computational biology, thresholding",
      toc: ["Header", "Lede", "Six markers, one panel", "Four ways to draw a line", "The marker that broke everything", "What 0.11 units hides"],
      sources: [
        ['[1] Otsu, N. (1979). ', '"A threshold selection method from gray-level histograms." IEEE Trans. Systems, Man, and Cybernetics.'],
        ['[2] Sharma, S. (2024). ', "Analysing and Advancing Automated Immune Biomarker Detection. MFoCS thesis, Oxford · Lady Margaret Hall."],
        ['[3] Wilson, C. M., et al. (2021). ', '"Challenges and opportunities in the statistical analysis of multiplex immunofluorescence data." Cancers 13(12).'],
      ],
      sidenotes: 4,
    },
    "constraint-clustering": {
      tags: "computational biology, clustering",
      toc: ["Header", "Lede", "Why not just threshold?", "What the textbook misses", "Teaching the distance metric", "The honest result"],
      sources: [
        ['[1] Ng, A., Jordan, M., & Weiss, Y. (2001). ', '"On spectral clustering: Analysis and an algorithm." NIPS 14.'],
        ['[2] Ward, J. H. (1963). ', '"Hierarchical grouping to optimize an objective function." J. American Statistical Association.'],
        ['[3] Sharma, S. (2024). ', "Analysing and Advancing Automated Immune Biomarker Detection. MFoCS thesis, Oxford · Lady Margaret Hall."],
        ['[4] Wagstaff, K. L. (2011). ', '"Constrained clustering." Encyclopedia of Machine Learning, Springer.'],
      ],
      sidenotes: 5,
    },
    "turing-morphogenesis": {
      tags: "mathematical biology, reaction-diffusion, morphogenesis",
      toc: ["Header", "Lede", "What the figure shows", "The condition", "Does it actually happen", "For Alan Turing"],
      sources: [
        ['[1] Turing, A.M. (1952). ', '"The Chemical Basis of Morphogenesis." Phil. Trans. R. Soc. Lond. B 237(641):37–72.'],
        ['[2] Castets, V., Dulos, E., Boissonade, J. & De Kepper, P. (1990). ', '"Experimental evidence of a sustained standing Turing-type nonequilibrium chemical pattern." Phys. Rev. Lett. 64(24):2953–2956.'],
        ['[3] Kondo, S. & Asai, R. (1995). ', '"A reaction-diffusion wave on the skin of the marine angelfish Pomacanthus." Nature 376:765–768.'],
        ['[4] Nakamasu, A. et al. (2009). ', '"Interactions between zebrafish pigment cells responsible for the generation of Turing patterns." PNAS 106(21):8429–8434.'],
        ['[5] Sick, S. et al. (2006). ', '"WNT and DKK determine hair follicle spacing through a reaction-diffusion mechanism." Science 314(5804):1447–1450.'],
        ['[6] Gierer, A. & Meinhardt, H. (1972). ', '"A theory of biological pattern formation." Kybernetik 12:30–39.'],
        ['[7] Gray, P. & Scott, S.K. (1983–84). ', 'Chem. Eng. Sci. 38(1):29–43 and 39(6):1087–1097.'],
      ],
      sidenotes: 7,
    },
    "fisher-wave": {
      tags: "mathematical biology, reaction-diffusion, travelling waves",
      toc: ["Header", "Lede", "What the figure shows", "For R. A. Fisher"],
      sources: [
        ['[1] Fisher, R. A. (1937). ', '"The wave of advance of advantageous genes." Annals of Eugenics 7:355–369.'],
        ['[2] Kolmogorov, A., Petrovsky, I. & Piskunov, N. (1937). ', '"A study of the diffusion equation with growth in the quantity of matter, and its application to a biological problem." Bull. Moscow State Univ. A 1:1–25.'],
        ['[3] Skellam, J. G. (1951). ', '"Random dispersal in theoretical populations." Biometrika 38:196–218.'],
        ['[4] Ammerman, A. J. & Cavalli-Sforza, L. L. (1971). ', '"Measuring the rate of spread of early farming in Europe." Man 6(4):674–688.'],
        ['[5] Murray, J. D. (2002). ', 'Mathematical Biology I: An Introduction. 3rd ed., Springer. §13.'],
        ['[6] Parthasarathy, R. (2016). ', 'Muskrat, 9 December 2016. Artwork, University of Oregon.'],
      ],
      sidenotes: 5,
    },
    "may-2026": {
      tags: "mathematical ecology, ODE, predator–prey",
      toc: ["Header", "Lede", "What the sliders teach", "For Robert May"],
      sources: [
        ['[1] Lotka, A. J. (1925). ', '"Elements of Physical Biology." Williams & Wilkins.'],
        ['[2] Volterra, V. (1926). ', '"Variazioni e fluttuazioni del numero d\'individui in specie animali conviventi." Mem. R. Acc. Lincei.'],
        ['[3] May, R. M. (1976). ', '"Simple mathematical models with very complicated dynamics." Nature 261.'],
      ],
      sidenotes: 4,
    },
    "six-engines": {
      tags: "recommendation, music, machine learning",
      toc: ["Header", "Lede", "Where it started: an undergrad free-reign brief", "Six engines, one query", "The dataset that made it tractable", "Why the ensemble works", "What the demo actually feels like"],
      sources: [
        ['[1] Reimers, N. & Gurevych, I. (2019). ', '"Sentence-BERT: Sentence Embeddings using Siamese BERT-Networks." EMNLP.'],
        ['[2] Mikolov, T., et al. (2013). ', '"Efficient estimation of word representations in vector space." arXiv 1301.3781.'],
        ['[3] Grover, A. & Leskovec, J. (2016). ', '"node2vec: Scalable feature learning for networks." KDD.'],
        ['[4] He, X., et al. (2017). ', '"Neural Collaborative Filtering." WWW 2017.'],
        ['[5] Chen, T., Kornblith, S., et al. (2020). ', '"A Simple Framework for Contrastive Learning of Visual Representations." ICML.'],
        ['[6] ', "github.com/shubhangithub/shubz-taylor-rec-engine-R · original R/Shiny version (2023)."],
        ['[7] ', "github.com/shubhangithub/updated-shubz-taylor-rec-engine · TypeScript + FastAPI rebuild (2026)."],
        ['[8] ', "shubz-taylor-recommendation-engine.vercel.app · live demo."],
      ],
      sidenotes: 3,
    },
    "zx-calculus": {
      tags: "quantum computation, ZX-calculus, physics",
      toc: ["Header", "Lede", "What circuits hide", "Spiders", "Three rules", "Why teleportation is obvious", "Completeness and what comes after"],
      sources: [
        ['[1] Coecke, B. & Duncan, R. (2008). ', '"Interacting Quantum Observables." ICALP 2008.'],
        ['[2] Coecke, B. & Duncan, R. (2011). ', '"Interacting Quantum Observables: Categorical Algebra and Diagrammatics." New Journal of Physics 13.'],
        ['[3] van de Wetering, J. (2020). ', '"ZX-calculus for the working quantum computer scientist." arXiv 2012.13966.'],
        ['[4] Kissinger, A. & van de Wetering, J. ', 'PyZX — Python library for ZX-calculus circuit optimisation. github.com/Quantomatic/pyzx'],
        ['[5] Jeandel, E., Perdrix, S. & Vilmart, R. (2018). ', '"A Complete Axiomatisation of the ZX-Calculus for Clifford+T Quantum Mechanics." LICS.'],
        ['[6] Coecke, B. & Kissinger, A. (2017). ', 'Picturing Quantum Processes. Cambridge University Press.'],
      ],
      sidenotes: 4,
    },
    "bluedot-assumptions": {
      tags: "ai strategy, epistemology, governance",
      toc: ["Header", "Lede", "Capability is scalar", "Compute is the binding lever", "The developer is well-intentioned", "Timelines are short", "Western actors write the rules", "Defence is the goal"],
      sources: [
        ['Chollet, F. (2019). ', '"On the Measure of Intelligence." arXiv 1911.01547. Dwarkesh Patel interview, Jun 2025.'],
        ['Aschenbrenner, L. (Jun 2024). ', '"Situational Awareness."'],
        ['Amodei, D. (Oct 2024). ', '"Machines of Loving Grace."'],
        ['Erdil, E. / Epoch (2025). ', '"A case for multi-decade AI timelines."'],
        ['Narayanan, A. & Kapoor, S. (Apr 2025). ', '"AI as Normal Technology." Knight First Amendment Institute.'],
        ['Kokotajlo et al. ', '"AI 2027" scenario.'],
        ['Nevo, S. et al. / RAND (2024). ', '"Securing AI Model Weights."'],
        ['Sarah / BlueDot (Apr 2025). ', '"Introduction to AI Control."'],
        ['Davidson, T., Finnveden, L. & Hadshar, R. (Apr 2025). ', '"AI-Enabled Coups." Forethought.'],
        ['Buterin, V. (Jan 2025). ', '"d/acc one year later."'],
        ['METR (Jan 2026). ', '"Time Horizon 1.1 update."'],
        ['ARC Prize Foundation (Feb 2026). ', 'ARC-AGI-2 and ARC-AGI-3 evaluation results.'],
      ],
      sidenotes: 1,
    },
    "bluedot-vocabulary": {
      tags: "ai strategy, language, policy",
      toc: ["Header", "Lede", "Alignment", "Coordination", "Race", "Control", "Safety", "Capability", "AGI"],
      sources: [
        ['Jones, A. / BlueDot (2025). ', '"What is AI alignment?"'],
        ['Aschenbrenner, L. (Jun 2024). ', '"Situational Awareness: IV. The Project."'],
        ['AI Treaty letter. ', 'aitreaty.org'],
        ['Buterin, V. (Jan 2025). ', '"d/acc one year later."'],
        ['Sarah / BlueDot (Apr 2025). ', '"Introduction to AI Control."'],
        ['Davidson, T. et al. (Apr 2025). ', '"AI-Enabled Coups." Forethought.'],
        ['Nevo, S. et al. / RAND (2024). ', '"Securing AI Model Weights."'],
        ['Samuel, S. / Vox (2024). ', '"It\'s Practically Impossible to Run a Big AI Company Ethically."'],
        ['Chollet, F. (2019). ', '"On the Measure of Intelligence." arXiv 1911.01547.'],
        ['ARC Prize Foundation (Mar 2026). ', 'ARC-AGI-3 release and evaluation.'],
        ['CAISI rebrand (Jun 2025). ', 'US Commerce Department announcement.'],
      ],
      sidenotes: 0,
    },
    "bluedot-civilization": {
      tags: "ai strategy, governance, civilisation",
      toc: ["Header", "Lede", "The Toner→Chollet move", "Four readings, one unit", "Sorting the course", "What shifts", "Honest tensions", "Why the frame matters"],
      sources: [
        ['Chollet, F. (2019, 2017). ', '"On the Measure of Intelligence"; "The impossibility of intelligence explosion."'],
        ['Buterin, V. (Jan 2025). ', '"d/acc one year later."'],
        ['Krook, J. (2023). ', '"Solarpunk: A Vision for a Sustainable Future."'],
        ['BlueDot (2025). ', '"Long list of interventions" — withstand layer.'],
        ['Narayanan, A. & Kapoor, S. (Apr 2025). ', '"AI as Normal Technology." Knight First Amendment Institute.'],
        ['Toner, H. (2024). ', '"In Search of a Dynamist Vision for Safe Superhuman AI." CSET.'],
        ['Davidson, T. et al. (Apr 2025). ', '"AI-Enabled Coups." Forethought.'],
        ['IFP — Fist, T. et al. (2024). ', '"Preparing for Launch." Institute for Progress.'],
        ['DeepMind (2024–2025). ', 'AlphaProteo (Sep 2024); AlphaFold 3 (Nature, May 2024); AlphaEvolve (May 2025).'],
        ['Clark, A. & Chalmers, D. (1998). ', '"The Extended Mind." Analysis 58(1).'],
        ['Hutchins, E. (1995). ', 'Cognition in the Wild. MIT Press.'],
        ['Hayek, F. A. (1945). ', '"The Use of Knowledge in Society." American Economic Review 35(4).'],
      ],
      sidenotes: 0,
    },
    "bluedot-killchain": {
      tags: "ai safety, control, alignment",
      toc: ["Header", "Lede", "Phase by phase", "Unit 1 visions", "Unit 2 empirical claims", "Unit 3–4 defences", "Unit 5 leverage"],
      sources: [
        ['Apollo Research (Dec 2024). ', '"Frontier Models are Capable of In-context Scheming."'],
        ['Anthropic (Dec 2024). ', 'Alignment-faking in large language models.'],
        ['Greenblatt, R. et al. (2023). ', '"AI Control: Improving Safety Despite Intentional Subversion." arXiv 2312.06942.'],
        ['Bhatt, U. et al. (2025). ', '"Ctrl-Z: Controlling AI Agents via Resampling."'],
        ['UK AISI. ', 'ControlArena evaluation framework.'],
        ['DeepMind (May 2025). ', 'AlphaEvolve.'],
        ['Becker, A. et al. (Jul 2025). ', '"METR developer productivity RCT." arXiv 2507.09089.'],
        ['Nevo, S. et al. / RAND (2024). ', '"Securing AI Model Weights."'],
        ['Amodei, D. (Oct 2024). ', '"Machines of Loving Grace."'],
        ['Toner, H. (2024). ', '"In Search of a Dynamist Vision for Safe Superhuman AI." CSET.'],
        ['Erdil, E. / Epoch (2025). ', 'Revenue per H100-equivalent analysis.'],
        ['ARC Prize Foundation (Mar 2026). ', 'ARC-AGI-3 release; 0.37% frontier model score.'],
        ['Ngo, R. (Oct 2024). ', '"Reframing AGI Threat Models." (2023) "AGI Safety Career Advice."'],
        ['Davidson, T. et al. (Apr 2025). ', '"AI-Enabled Coups." Forethought.'],
        ['Anthropic (2024–2025). ', '"Scaling Monosemanticity" (May 2024); "The Urgency of Interpretability" (Apr 2025).'],
        ['Nanda, N. ', '"Become a person who Actually Does Things."'],
        ['FLI / Eisenpress (Feb 2024). ', '"Catastrophic AI Scenarios."'],
      ],
      sidenotes: 1,
    },
    "bluedot-unit1": {
      tags: "ai strategy, policy, safety",
      toc: ["Header", "Lede", "The prize", "The structural obstacle", "What shaping actually looks like", "The international complication", "What kind of future, exactly?", "Who is 'we'?"],
      sources: [
        ['[1] Rehman, I., Mueller, K., Mazarr, M. (2024). ', '"Seeking Stability in the Competition for AI Advantage." RAND Corporation.'],
        ['[2] Samuel, S. (2024). ', '"It\'s Practically Impossible to Run a Big AI Company Ethically." Vox.'],
        ['[3] Toner, H. (2024). ', '"In Search of a Dynamist Vision for Safe Superhuman AI." CSET.'],
        ['[4] Fist, T., Burga, A., Hwang, T. (2024). ', '"Preparing for Launch." Institute for Progress.'],
        ['[5] Bregman, R. (2017). ', '"The Return of Utopia." Ch. 1 in Utopia for Realists. Little, Brown.'],
        ['[6] Amodei, D. (2024). ', '"Machines of Loving Grace." Personal essay, October 2024.'],
        ['[7] Altman, S. (2025). ', '"The Gentle Singularity." Personal essay, June 2025.'],
        ['[8] Altman, S. (2024). ', '"The Intelligence Age." Personal essay, September 2024.'],
        ['[9] Krook, J. (2023). ', '"Solarpunk: A Vision for a Sustainable Future."'],
      ],
      sidenotes: 5,
    },
    "fashion-trends": {
      tags: "forecasting, computer vision, LMSR",
      toc: ["Header", "Lede", "Five signals, one composite", "The Trend Exchange", "What the camera sees", "What I'm optimising for"],
      sources: [
        ['[1] Hanson, R. (2003). ', '"Combinatorial Information Market Design." Information Systems Frontiers.'],
        ['[2] ', "fashion-web-psi.vercel.app — live platform, Next.js / Vercel edge / LMSR exchange."],
        ['[3] ', "Google Trends (trendspyg), Bluesky firehose, Pinterest, Reddit, YouTube — five-source ingestion pipeline."],
        ['[4] ', "Gemini 2.5 Flash — garment detection, colour palette extraction, runway matching."],
      ],
      sidenotes: 3,
    },
  };
  return meta[slug] || meta["jaya"];
}
